# Generated by Django 3.2.3 on 2021-06-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=250)),
                ('confirmed', models.IntegerField(max_length=50)),
                ('curConfirmed', models.IntegerField(max_length=50)),
                ('died', models.IntegerField(max_length=50)),
                ('cured', models.IntegerField(max_length=50)),
                ('confirmedRelative', models.IntegerField(max_length=50)),
            ],
        ),
    ]
